### ISSUE TITLE
Project can't be built

### ISSUE THREAD

**Issue by Artur-** [vaadin/board#63]
Running
`mvn clean install`
on a newly cloned project does not work.

There are a lot of 
```
Running com.vaadin.addon.board.testbenchtests.RowRemoveIT
java.io.FileNotFoundException: config/testbench.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.vaadin.addon.board.testUI.UIFunctions.readProperties(UIFunctions.java:18)
	at com.vaadin.addon.board.testUI.UIFunctions.readTestbenchProperties(UIFunctions.java:31)
	at com.vaadin.addon.board.testbenchtests.AbstractParallelTest.setUp(AbstractParallelTest.java:32)
```

**Comment by rogozinds** [comment]
git clone
mvn clean install works in master
Can you check master please?
